name: Clean Docx Files

on:
  push:
    paths:
      - 'legal_docs/**'

jobs:
  clean-docx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-docx

    - name: Run docx cleaner
      run: python convert_docx_to_txt.py

    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: training-data
        path: training_data.txt
